create table anggota (
   id_anggota    number generated by default as identity primary key,
   nama          varchar2(100) not null,
   jenis_kelamin char(1) check ( jenis_kelamin in ( 'L',
                                                    'P' ) ),
   alamat        varchar2(200)
);

create table buku (
   id_buku      number generated by default as identity primary key,
   judul        varchar2(150) not null,
   pengarang    varchar2(100) not null,
   penerbit     varchar2(100),
   tahun_terbit number(4),
   stok         number default 0 check ( stok >= 0 )
);

create table peminjaman (
   id_peminjaman   number generated by default as identity primary key,
   id_anggota      number not null,
   id_buku         number not null,
   tanggal_pinjam  date not null,
   tanggal_kembali date,
   status          varchar2(20) default 'Dipinjam' check ( status in ( 'Dipinjam',
                                                              'Dikembalikan' ) ),
   constraint fk_peminjaman_anggota foreign key ( id_anggota )
      references anggota ( id_anggota ),
   constraint fk_peminjaman_buku foreign key ( id_buku )
      references buku ( id_buku )
);